
package GUI;

import com.sun.j3d.utils.universe.SimpleUniverse;
import javax.media.j3d.Canvas3D;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;

/**
 *
 * @author fvelasco
 */
public class ControlWindow extends JFrame {
  private SimpleUniverse universe;

  public ControlWindow(Canvas3D canvas, SimpleUniverse anUniverse) {
    super();
    universe = anUniverse;
    initComponents();
    setLocation (920, 100);
    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        closeApp(0);
      }
    });
    Visualization visualization = new Visualization (this, false, canvas);
    visualization.setVisible(true);
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    primitiveGroup = new javax.swing.ButtonGroup();
    appearanceGroup = new javax.swing.ButtonGroup();
    primitivePanel = new javax.swing.JPanel();
    cube = new javax.swing.JRadioButton();
    sphere = new javax.swing.JRadioButton();
    appearancesPanel = new javax.swing.JPanel();
    color = new javax.swing.JRadioButton();
    texture = new javax.swing.JRadioButton();
    lightsPanel = new javax.swing.JPanel();
    light1 = new javax.swing.JCheckBox();
    light2 = new javax.swing.JCheckBox();
    optionsPanel = new javax.swing.JPanel();
    rotation = new javax.swing.JToggleButton();
    axes = new javax.swing.JToggleButton();
    commandsPanel = new javax.swing.JPanel();
    exitApp = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Control");
    setMinimumSize(new java.awt.Dimension(300, 345));
    getContentPane().setLayout(new java.awt.GridLayout(5, 0));

    primitivePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Primitivas"));
    primitivePanel.setLayout(new java.awt.GridLayout(2, 0));

    primitiveGroup.add(cube);
    cube.setSelected(true);
    cube.setText("Cubo");
    cube.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cubeActionPerformed(evt);
      }
    });
    primitivePanel.add(cube);

    primitiveGroup.add(sphere);
    sphere.setText("Esfera");
    sphere.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sphereActionPerformed(evt);
      }
    });
    primitivePanel.add(sphere);

    getContentPane().add(primitivePanel);

    appearancesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Materiales"));
    appearancesPanel.setLayout(new java.awt.GridLayout(2, 0));

    appearanceGroup.add(color);
    color.setSelected(true);
    color.setText("Color");
    color.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        colorActionPerformed(evt);
      }
    });
    appearancesPanel.add(color);

    appearanceGroup.add(texture);
    texture.setText("Textura");
    texture.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        textureActionPerformed(evt);
      }
    });
    appearancesPanel.add(texture);

    getContentPane().add(appearancesPanel);

    lightsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Luces"));

    light1.setSelected(true);
    light1.setText("Principal");
    light1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        light1ActionPerformed(evt);
      }
    });
    lightsPanel.add(light1);

    light2.setSelected(true);
    light2.setText("Secundaria");
    light2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        light2ActionPerformed(evt);
      }
    });
    lightsPanel.add(light2);

    getContentPane().add(lightsPanel);

    optionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones"));

    rotation.setSelected(true);
    rotation.setText("Rotación");
    rotation.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        rotationActionPerformed(evt);
      }
    });
    optionsPanel.add(rotation);

    axes.setSelected(true);
    axes.setText("Mostrar Ejes");
    axes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        axesActionPerformed(evt);
      }
    });
    optionsPanel.add(axes);

    getContentPane().add(optionsPanel);

    commandsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

    exitApp.setText("Salir");
    exitApp.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitAppActionPerformed(evt);
      }
    });
    commandsPanel.add(exitApp);

    getContentPane().add(commandsPanel);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeActionPerformed
    // TODO add your handling code here:
   // universe.setPrimitive(PrimitiveBranches.Cube);
  }//GEN-LAST:event_cubeActionPerformed

  private void sphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphereActionPerformed
    // TODO add your handling code here:
    //universe.setPrimitive(PrimitiveBranches.Ball);
  }//GEN-LAST:event_sphereActionPerformed

  private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
    // TODO add your handling code here:
    //universe.setAppearance(Appearances.Color);
  }//GEN-LAST:event_colorActionPerformed

  private void textureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textureActionPerformed
    // TODO add your handling code here:
    //universe.setAppearance (Appearances.Texture);
  }//GEN-LAST:event_textureActionPerformed

  private void light1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_light1ActionPerformed
    // TODO add your handling code here:
    //universe.setLightsOnOff(1, light1.isSelected());
  }//GEN-LAST:event_light1ActionPerformed

  private void light2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_light2ActionPerformed
    // TODO add your handling code here:
    //universe.setLightsOnOff(2, light2.isSelected());
  }//GEN-LAST:event_light2ActionPerformed

  private void rotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotationActionPerformed
    // TODO add your handling code here:
   // universe.setRotationOnOff(rotation.isSelected());
  }//GEN-LAST:event_rotationActionPerformed

  private void exitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppActionPerformed
    // TODO add your handling code here:
    closeApp(0);
  }//GEN-LAST:event_exitAppActionPerformed

  private void axesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axesActionPerformed
    // TODO add your handling code here:
    //universe.showAxes(axes.isSelected());
  }//GEN-LAST:event_axesActionPerformed

  public void showWindow () {
    setVisible (true);
  }

  void closeApp (int code) {
   System.exit (code);
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup appearanceGroup;
  private javax.swing.JPanel appearancesPanel;
  private javax.swing.JToggleButton axes;
  private javax.swing.JRadioButton color;
  private javax.swing.JPanel commandsPanel;
  private javax.swing.JRadioButton cube;
  private javax.swing.JButton exitApp;
  private javax.swing.JCheckBox light1;
  private javax.swing.JCheckBox light2;
  private javax.swing.JPanel lightsPanel;
  private javax.swing.JPanel optionsPanel;
  private javax.swing.ButtonGroup primitiveGroup;
  private javax.swing.JPanel primitivePanel;
  private javax.swing.JToggleButton rotation;
  private javax.swing.JRadioButton sphere;
  private javax.swing.JRadioButton texture;
  // End of variables declaration//GEN-END:variables
}
